apiVersion: v1
kind: Service
metadata:
  name: directory-explorer-service
spec:
  selector:
    app: directory-explorer
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: directory-explorer
spec:
  selector:
    matchLabels:
      app: directory-explorer
  replicas: 4
  template:
    metadata:
      labels:
        app: directory-explorer
    spec:
      containers:
      - name: directory-explorer
        image: blacksmithop/directory-explorer:main
        imagePullPolicy: Never
        ports:
        - containerPort: 80